// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrgwX7JyQJJw_K-1ahdEQZa62rIfeB6sE',
    appId: '1:95188603174:web:4675eb8657506be6ab31e7',
    messagingSenderId: '95188603174',
    projectId: 'meals-project-6294e',
    authDomain: 'meals-project-6294e.firebaseapp.com',
    storageBucket: 'meals-project-6294e.firebasestorage.app',
    measurementId: 'G-J8VXMC3B11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAElbLCGVtoXmElV2meAW2o_OF58VY5UbM',
    appId: '1:95188603174:android:5bd24c45d08f5bd7ab31e7',
    messagingSenderId: '95188603174',
    projectId: 'meals-project-6294e',
    storageBucket: 'meals-project-6294e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnrwfiE0Bl1OE5HIH1x2NX8YMG2n5CfHw',
    appId: '1:95188603174:ios:b6753ea5f2b20fc9ab31e7',
    messagingSenderId: '95188603174',
    projectId: 'meals-project-6294e',
    storageBucket: 'meals-project-6294e.firebasestorage.app',
    iosBundleId: 'com.example.mis2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnrwfiE0Bl1OE5HIH1x2NX8YMG2n5CfHw',
    appId: '1:95188603174:ios:b6753ea5f2b20fc9ab31e7',
    messagingSenderId: '95188603174',
    projectId: 'meals-project-6294e',
    storageBucket: 'meals-project-6294e.firebasestorage.app',
    iosBundleId: 'com.example.mis2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrgwX7JyQJJw_K-1ahdEQZa62rIfeB6sE',
    appId: '1:95188603174:web:3afb18f9a6a82d0dab31e7',
    messagingSenderId: '95188603174',
    projectId: 'meals-project-6294e',
    authDomain: 'meals-project-6294e.firebaseapp.com',
    storageBucket: 'meals-project-6294e.firebasestorage.app',
    measurementId: 'G-C8X7NZL4WM',
  );
}
